public class Constants {
	//////////////////////////////////////////// Milestone Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	public static final String PUBLISH_DATE_MILESTONE_NAME = 'Publish Date';
	public static final String START_DATE_MILESTONE_NAME = 'Start Date';
	public static final String REGISTRATION_DATE_MILESTONE_NAME = 'Registration Date';
	public static final String SUBMISSION_DATE_MILESTONE_NAME = 'Submission Date';
	public static final String REVIEW_DATE_MILESTONE_NAME = 'Review Date';
	public static final String END_DATE_MILESTONE_NAME = 'End Date';
	////////////////////////////////////////// END Milestone Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	//////////////////////////////////////////// Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	public static final String READY_TO_REVIEW_STATUS = 'Ready to Review';
	public static final String REVIEW_COMPLETE_STATUS = 'Review Complete';
	////////////////////////////////////////// END Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	

}