public class Constants {
	//////////////////////////////////////////// Milestone Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	public static final String PUBLISH_DATE_MILESTONE_NAME = 'Publish Date';
	public static final String START_DATE_MILESTONE_NAME = 'Start Date';
	public static final String REGISTRATION_DATE_MILESTONE_NAME = 'Registration Date';
	public static final String ASSIGNMENT_DATE_MILESTONE_NAME = 'Assignment Date';
	public static final String SUBMISSION_DATE_MILESTONE_NAME = 'Submission Date';
	public static final String REVIEW_DATE_MILESTONE_NAME = 'Review Date';
	public static final String ACCEPTANCE_DATE_MILESTONE_NAME = 'Acceptance Date';
	public static final String END_DATE_MILESTONE_NAME = 'End Date';
	
	////////////////////////////////////////// END Milestone Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	//////////////////////////////////////////// Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	public static final String READY_TO_REVIEW_STATUS = 'Ready to Review';
	public static final String REVIEW_COMPLETE_STATUS = 'Review Complete';
	////////////////////////////////////////// END Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	//////////////////////////////////////////// Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	public static final String STORY_PLANNING_STATUS = 'Planning';
	public static final String STORY_COMPLETED_STATUS = 'Completed';
	////////////////////////////////////////// END Submission Constants \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
	// Activity Status Constants
	public static final String STATUS_DRAFT = 'Draft';
	public static final String STATUS_PUBLIC = 'Public';
	public static final String STATUS_IN_REGISTRATION = 'In Registration';
	public static final String STATUS_IN_ASSIGNMENT = 'In Assignment';
	public static final String STATUS_IN_SUBMISSION = 'In Submission';
	public static final String STATUS_IN_REVIEW = 'In Review';
	public static final String STATUS_ACCEPTED = 'Accepted';
	public static final String STATUS_COMPLETE = 'Complete';
	public static final String STATUS_CANCELED = 'Canceled';

	public static final Map<String, Integer> REQUIRMENT_SCORE_BY_WEIGHT = new Map<String, Integer>{'High' => 3, 'Medium' => 2, 'Low' => 1};

	public static final String PUBLISHER = 'Publisher';
}